# This is a comment

somename: value # this is also a comment

anothername: '#value'

#example Spring Properties
#spring.datasource.initial-size=1
#spring.datasource.max-active=10
#spring.datasource.min-idle=1
#spring.datasource.max-idle=5

#Example Spring Properties in YAML
spring:
  datasource:
    initial-size: 1
    max-active: 10
    min-idle: 1
    max-idle: 5

# list syntax
somelist:
- value1: one
- value2: two

# Alternate list syntax
somelist2:
  - value1: one
  - value2: two

#List of maps
anothermaplist:
  - keyvalue: 1
    value: 'my val'
  - keyvalue: 2
    value: 'my val'